name: movielistapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  anim_search_bar: ^2.0.2
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.1
  google_fonts: ^2.3.1
  intl: ^0.17.0
  persistent_bottom_nav_bar: ^4.0.2
  responsive_sizer: ^3.0.5+1
  youtube_player_flutter: ^8.0.0
  zoom_widget: ^0.2.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true
